# Generated by Django 5.0.3 on 2024-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
