# Generated by Django 5.0.3 on 2024-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
