# Generated by Django 5.0.3 on 2024-03-25 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('about', models.TextField(max_length=100)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Software developer', 'Software developer'), ('Project Leader', 'Project Leader')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
